import { Roboto, Raleway, Lato, Inter } from "next/font/google";
import "./globals.css";
import LoginModal from "@/components/LoginModal";
import { NextAuthSessionProvider } from "@/components/nextauthProvider";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

// const roboto = Roboto({ subsets: ["latin"] });
// const lato = Lato({ subsets: ["latin"] });
// const raleway = Raleway({ subsets: ["latin"] });
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* ${roboto.className} ${raleway.className} ${lato.className}  */}
      <body className={`
      ${inter.className}`}>
        <ToastContainer position="top-center"
          autoClose={5000}
          hideProgressBar
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover />
        <NextAuthSessionProvider>
          {children}
          <LoginModal />
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
